### PR TITLE
fix tests and some bugs

### PR DESCRIPTION
**Pull request by ntsvetanov**
Hey @lukedeo  

I've found some bugs- if you pass at last position multi arg the code crashed. There was a problem with some tests. I've fixed them, add more tests and refactor the code

### CODE REVIEW

**Comment by lukedeo** [comment]
Hi @ntsvetanov can you rebase your changes with master? Things have diverged a bit.

**Comment by lukedeo** [comment]
As is, it is hard to view the diff. I think it will be a bit easier once a rebase is done.

Thanks for the fixes, by the way! I see tests are now on both Mac & Linux on Travis.

**Comment by ntsvetanov** [comment]
There was a problem with whitespaces. With last commit Ive removed it from some files. 
Aslo there is such problem in optionparser.h and i can't figure out how to fix it fast. If you want use my version of the file. You can hide whitespace diff in pull request files changed menu. 

P.S. Sorry for my bad english

**Comment by ntsvetanov** [comment]
If you want I can refactor the code a little bit more and I can add additional tests.

**Comment by lukedeo** [comment]
@ntsvetanov no worries, thanks for the contribution! I will merge this from the command line. It seems that the massive newline diffs are due to Windows - are you developing on Windows? `^M` characters (for carriage return) are getting added in place...

No worries though, will merge manually and do a rebase to clean up the history.

**Comment by lukedeo** [comment]
Merged manually! Thanks again 👍

**Pull request closed without merging**
